import { Product } from "@/types/product.types";

export const products: Array<Product> = [
  {
    id: 601278761,
    slug: "bolsa-mini-bag-com-bolso-com-ziper-e-alca-com-mosquetoes",
    price: 9990,
    summary: '<p>Bolsa mini bag com bolso com zíper e alça com mosquetões. Discreta mas estilosa, a peça dá o toque final a qualquer look mais casual.&nbsp;</p><p><strong>ESPECIFICAÇÕES DO PRODUTO</strong></p><ul><li>Bolsa masculina</li><li>Modelo mini bag</li><li>Com bolso com zíper</li><li>Fechamento por botões</li><li>Alças com mosquetões</li><li>Marca: Viko</li><li>Tecido: Poliéster</li><li>Composição: 100% Poliéster</li><li>Composição forro: 100% Poliéster</li></ul><p><strong>O TECIDO QUE AMAMOS</strong><br />Um marco na indústria têxtil, o poliéster foi o grande responsável pela criação de uma moda jovem e surgimento das tendências, isso lá nos anos 1960 - amém, poliéster! Uma característica importante é a memória de forma, que livra a peça daqueles amassados desgradáveis, motivo pelo qual a fibra é mesclada com outras não tão fortes nesse quesito, como o linho e algodão. Muita tecnologia foi aplicada no desenvolvimento do material nos últimos 60 anos, e as possibilidades são várias: de tecidos com toque e visual acetinado aos de alta performance, leves e respiráveis, ideais para o sportwear.</p><p><strong>COLEÇÃO OUTONO/INVERNO 2022&nbsp;</strong></p>',
    name: 'Bolsa Mini Bag com Bolso com Zíper e Alça com Mosquetões',
    stock_amount: 50,
    image: 'https://img.lojasrenner.com.br/item/601278761/medium/1.jpg',
    description: 'Bolsa mini bag com bolso com zíper e alça com mosquetões. Discreta mas estilosa, a peça dá o toque final a qualquer look mais casual',
  },
  {
    id: 601253978,
    slug: "mochila-puffer-com-bolso-frontal",
    price: 18990,
    summary: '<p>Mochila puffer com duas alças, dois bolsos frontais e etiqueta aplicada com logo da marca. Leve seus pertences para onde quiser com total estilo e conforto. A mochila conta com vários compartimentos além do design com gomos, típico do modelo puffer, que faz dela um item indispensável para&nbsp;quem preza por elegância até nos acessórios.</p><p><strong>ESPECIFICAÇÕES DO PRODUTO</strong></p><ul><li>Mochila masculina</li><li>Modelo puffer</li><li>Fechamento em zíper</li><li>Duas alças</li><li>02 bolsos frontais</li><li>Marca: Viko</li><li>Material: Poliamida</li><li>Composição: 100% Poliéster</li><li>Composição forro 100% Poliéster</li></ul><p><strong>COLEÇÃO OUTONO/INVERNO 2022&nbsp;</strong></p>',
    name: 'Mochila Puffer com Bolso Frontal Preto',
    stock_amount: 2,
    image: 'https://img.lojasrenner.com.br/item/601253978/medium/1.jpg',
    description: 'Mochila puffer com duas alças, dois bolsos frontais e etiqueta aplicada com logo da marca. Leve seus pertences para onde quiser com total estilo e conforto. ',
  },
  {
    id: 625894614,
    slug: "bolsa-tote-com-bolso-externo-com-ziper",
    price: 19990,
    summary: '<p>Bolsa tote com bolso externo com zíper. A bolsa tote é conhecida como uma bolsa-sacola grande, aberta, que é perfeita para guardar vários itens dentro dela. Este modelo ainda conta com um bolso externo com zíper para guardar seus pertences pessoais. O acessório é versátil além de puro luxo!</p><p><strong>ESPECIFICAÇÕES DO PRODUTO</strong></p><ul><li>Bolsa masculina</li><li>Modelo tote</li><li>Com duas alças finas</li><li>Bolso externo com zíper</li><li>Marca: Viko</li><li>Material e Processo Sustentáveis</li><li>Tecido: Mistura de materiais</li><li>Composição: 65% Algodão 35% Poliuretano</li></ul><p><strong>O TECIDO QUE AMAMOS</strong><br />O Algodão é uma fibra longa e esbranquiçada, uma velha conhecida até dos menos entendidos de tecidos – impossível não associá-lo a uma camiseta básica, né? Com atributos como conforto, durabilidade e maciez, é utilizado há séculos para confecção de roupas. Diversos tecidos são feitos a partir do algodão, como tricoline, crepe, flanela e sarja, por exemplo.</p><p><strong>MODA RESPONSÁVEL</strong><br />Confeccionado com algodão produzido respeitando requisitos e boas práticas de responsabilidade socioambiental, tais como as iniciativas: BCI, ABR, algodão agroecológico, algodão orgânico, entre outras.<br />•BCI: O algodão com a certificação BCI foi produzido levando em conta critérios como direitos trabalhistas, uso consciente da água, produtos químicos e defensivos agrícolas. Quem faz a avaliação dessas condições é a Better Cotton Initiative (BCI), uma organização global sem fins lucrativos.<br />•ABR (Algodão Brasileiro Responsável): O programa ABR é coordenado pela ABRAPA (Associação Brasileira dos Produtores de Algodão) para promover a sustentabilidade na cultura do algodão brasileiro visando proteger e preservar a integridade do trabalhador; adquirir e manter as boas práticas que combinam a produção agrícola e a preservação do meio ambiente visando preservar nossas principais reservas naturais, em especial a Amazônia, o Pantanal e a Mata Atlântica; e fazer do algodão responsável um negócio rentável para o produtor.<br />•Algodão agroecológico: Cultivo que emprega práticas de conservação do solo e da água, aonde o plantio é consorciado com outras culturas e são utilizados protetores naturais no controle de pragas. Produzido por mulheres do norte de Minas Gerais apoiadas pelo Instituto Lojas Renner.<br />•Algodão orgânico: Não emprega produtos químicos sintéticos, como fertilizantes sintéticos solúveis, agrotóxicos, adubos químicos e transgênicos. Organic Content Standard (OCS), Global Organic Textile Standard (GOTS), Ecocert e IBD estão entre as certificações.<br />•Outras iniciativas também são aceitas, como: Cotton Connect, Fair Trade e Made in Africa.</p><p><strong>COLEÇÃO OUTONO/INVERNO 2022</strong></p>',
    name: 'Material Sustentável Bolsa Tote com Bolso Externo com Zíper Bege/Preto',
    stock_amount: 0,
    image: 'https://img.lojasrenner.com.br/item/625894614/medium/1.jpg',
    description: 'Bolsa tote com bolso externo com zíper. A bolsa tote é conhecida como uma bolsa-sacola grande, aberta, que é perfeita para guardar vários itens dentro dela.',
  },
  {
    id: 621605846,
    slug: "guarda-chuva-com-abertura-automatica-e-saco-para-guardar-com-alca",
    price: 13990,
    summary: '<p>Guarda-chuva com abertura automática e saco para guardar com alça. Prático e eficiente, o produto&nbsp;não perde nada em estilo e vem ainda com saco para guardar com alça. Elegância e completa funcionalidade para os dias chuvosos!</p><p><strong>ESPECIFICAÇÕES DO PRODUTO</strong></p><ul><li>Guarda-chuva</li><li>Abertura automática</li><li>Ssaco para guardar com alça</li><li>Marca: Viko</li><li>Material: Poliamida e poliéster</li><li>Composição cabo: 100% Poliamida Tecido 100% Poliéster</li></ul><p><strong>COLEÇÃO OUTONO/INVERNO 2022</strong></p>',
    name: 'Guarda-chuva com abertura automática e saco para guardar com alça',
    stock_amount: 12,
    image: 'https://img.lojasrenner.com.br/item/621605846/medium/1.jpg',
    description: 'Guarda-chuva com abertura automática e saco para guardar com alça. Prático e eficiente, o produto&nbsp;não perde nada em estilo e vem ainda com saco para guardar com alça.',
  },
  {
    id: 571171778,
    slug: "cinto-lona-com-meia-argola",
    price: 1990,
    summary: '<p>Cinto em lona com ajuste por fivela. Acessório super prático e necessário para você que busca o parceiro para os seus looks diários.&nbsp;</p><p><strong>ESPECIFICAÇÕES DO PRODUTO</strong></p><ul><li>Cinto masculino</li><li>Com fivela</li><li>Nivelamento de ajuste</li><li>Marca: Viko</li><li>Tecido: Algodão com elastano</li><li>Composição: 45% Poliester 45% Elastano 10% Poliuretano</li></ul><p><strong>COLEÇÃO OUTONO/INVERNO 2022&nbsp;</strong></p>',
    name: 'Cinto Lona com Meia Argola Preto',
    stock_amount: 2,
    image: 'https://img.lojasrenner.com.br/item/571171778/medium/1.jpg',
    description: 'Cinto em lona com ajuste por fivela. Acessório super prático e necessário para você que busca o parceiro para os seus looks diários.',
  },
  {
    id: 622201616,
    slug: "bone-em-algodao-com-lettering-bordado-stark-industries-e-marvel",
    price: 2199,
    summary: '<p>Boné, em algodão, com aba curva e estampa bordada com lettering "Stark Industries" e "Marvel". Aos amantes da franquia Marvel, em especial, do "gênio, bilionário, playboy e filantropo"&nbsp;mais famoso do mundo dos super heróis, Tony Stark, esta peça não pode faltar na coleção.&nbsp;</p><p><strong>ESPECIFICAÇÕES DO PRODUTO</strong></p><ul><li>Boné masculino</li><li>Aba curva&nbsp;</li><li>Fechamento em snapcback</li><li>Estampa bordada na frente e atrás</li><li>Marca: Marvel</li><li>Material Sustentável</li><li>Tecido: Algodão</li><li>Composição: 100% Algodão</li></ul><p><strong>O TECIDO QUE AMAMOS</strong><br />O Algodão é uma fibra longa e esbranquiçada, uma velha conhecida até dos menos entendidos de tecidos – impossível não associá-lo a uma camiseta básica, né? Com atributos como conforto, durabilidade e maciez, é utilizado há séculos para confecção de roupas. Diversos tecidos são feitos a partir do algodão, como tricoline, crepe, flanela e sarja, por exemplo.</p><p><strong>MODA RESPONSÁVEL</strong><br />Confeccionado com algodão produzido respeitando requisitos e boas práticas de responsabilidade socioambiental, tais como as iniciativas: BCI, ABR, algodão agroecológico, algodão orgânico, entre outras.<br />•BCI: O algodão com a certificação BCI foi produzido levando em conta critérios como direitos trabalhistas, uso consciente da água, produtos químicos e defensivos agrícolas. Quem faz a avaliação dessas condições é a Better Cotton Initiative (BCI), uma organização global sem fins lucrativos.<br />•ABR (Algodão Brasileiro Responsável): O programa ABR é coordenado pela ABRAPA (Associação Brasileira dos Produtores de Algodão) para promover a sustentabilidade na cultura do algodão brasileiro visando proteger e preservar a integridade do trabalhador; adquirir e manter as boas práticas que combinam a produção agrícola e a preservação do meio ambiente visando preservar nossas principais reservas naturais, em especial a Amazônia, o Pantanal e a Mata Atlântica; e fazer do algodão responsável um negócio rentável para o produtor.<br />•Algodão agroecológico: Cultivo que emprega práticas de conservação do solo e da água, aonde o plantio é consorciado com outras culturas e são utilizados protetores naturais no controle de pragas. Produzido por mulheres do norte de Minas Gerais apoiadas pelo Instituto Lojas Renner.<br />•Algodão orgânico: Não emprega produtos químicos sintéticos, como fertilizantes sintéticos solúveis, agrotóxicos, adubos químicos e transgênicos. Organic Content Standard (OCS), Global Organic Textile Standard (GOTS), Ecocert e IBD estão entre as certificações.<br />•Outras iniciativas também são aceitas, como: Cotton Connect, Fair Trade e Made in Africa.</p><p><strong>COLEÇÃO OUTONO/INVERNO 2022&nbsp;</strong></p>',
    name: 'Material Sustentável Boné em Algodão com Lettering Bordado Preto',
    stock_amount: 2,
    image: 'https://img.lojasrenner.com.br/item/622201616/medium/1.jpg',
    description: 'Boné, em algodão, com aba curva e estampa bordada com lettering "Stark Industries" e "Marvel".',
  },
]