import { Header, BuyButton } from '@/components'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from "./produto.module.css"

const Produto: NextPage = () => {
  const router = useRouter()
  const { slug } = router.query

  const produto = {
    slug: "produto-teste",
    price: 2199,
    description: '',
    name: '',
    stock_amount: '',
    image: '',
    summary: '',
  }
  return (
    <div className={styles.product}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <img src="" alt="" className={styles.image} />
      <h1 className={styles.title}>Nome do produto</h1>
      <hr />
      <div className={styles.actions}>
        <div className={styles.price}>
          <span className={styles.price__full}>R$129,90</span>
          <span className={styles.price__installments}>
            Ou em até 12x de <strong>R$12,99</strong>
          </span>
        </div>
        <BuyButton></BuyButton>
      </div>

      <hr />

      <div className={styles['section-title']}>DETALHES</div>
      <div className={styles.details}></div>
    </div>
  )
}

export default Produto
